[package]
name = "cargo-msrv-reporter"
description = "User facing output of cargo-msrv"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

rust-version = "1.91.1"

keywords = ["msrv", "rust-version", "cargo-msrv", "reporter", "minimum"]
categories = ["development-tools", "development-tools::cargo-plugins"]

[dependencies]
cargo-msrv-context = { workspace = true }
cargo-msrv-manifest = { workspace = true }
cargo-msrv-types = { workspace = true }

camino = "1.2"
cargo_metadata = "0.23.1"
indicatif = "0.18.4"
owo-colors = "4.3.0"
petgraph = "0.8.3"
semver = "1.0"
serde = { workspace = true }
serde_json = "1.0.150"
storyteller = "2.0.0-beta.1"
tabled = { version = "~0.16.0", features = ["ansi"] }
terminal_size = "0.4.3"

[dev-dependencies]
yare = { workspace = true }

[features]
# Enables the `rust-dist` release source
rust-releases-dist-source = ["cargo-msrv-context/rust-releases-dist-source"]

# Enables the test reporters and event handlers, for use by dependent crates
testing = []
