accepted = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-3.0",
    "Zlib",
]
workarounds = ["ring", "rustls"]

ignore-build-dependencies = true
ignore-dev-dependencies = true

[option-ext]
accepted = ["MPL-2.0"]

[ring]
accepted = ["ISC", "OpenSSL"]

[webpki-roots]
accepted = ["CDLA-Permissive-2.0"]
