[package]
name = "v_unbuildable"
version = "0.1.0"
authors = ["foresterre <garm@ilumeo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
