[package]
name = "cargo-msrv-types"
description = "Common types of cargo-msrv"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

rust-version = "1.91.1"

keywords = ["msrv", "rust-version", "cargo-msrv", "types", "minimum"]
categories = ["development-tools", "development-tools::cargo-plugins"]

[dependencies]
semver = "1.0"
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rust-releases = { workspace = true }
yare = { workspace = true }
