name: "ci-linter"
on:
  pull_request:
  push:
    branches:
      - master
      - main
  merge_group:
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: check_clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets --workspace
